when:
  - event: [push, manual]
    branch: main

volumes:
  - name: gradle-cache
    driver: local

steps:
  - name: gradle-build
    image: eclipse-temurin:25-jdk-alpine
    volumes:
      - name: gradle-cache
        path: /root/.gradle
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=false -Xmx1g"
      GRADLE_USER_HOME: "/root/.gradle"
    commands:
      - ./gradlew bootJar -x test --build-cache --no-daemon

  - name: image-build-and-push
    image: woodpeckerci/plugin-kaniko
    settings:
      registry: registry.melkassib.dev
      repo: spring-api-k8s-demo
      dockerfile: Dockerfile
      context: .
      tags:
        - latest
        - ${CI_COMMIT_SHA:0:7}

      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

      build_args:
        - JAR_FILE=build/libs/*.jar

      snapshot_mode: redo
      use_new_run: true

      cache: true
      cache_repo: registry.melkassib.dev/kaniko-cache